name: Build OpenWrt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt update && sudo apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

    - name: Clone OpenWrt repository
      run: git clone https://github.com/openwrt/openwrt.git

    - name: Add custom feeds
      run: |
        echo 'src-git small_package https://github.com/kenzok8/small-package.git' >> openwrt/feeds.conf.default

    - name: Update Feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load Custom Configuration
      run: |
        cp ./config/default.config openwrt/.config
        cd openwrt
        make defconfig

    - name: Compile OpenWrt
      run: |
        cd openwrt
        make -j1 V=s

    - name: Archive Production Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: openwrt-image
        path: openwrt/bin